version: '3.8'

services:
  event_agent:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A dvalin_tools.agents.event_agent worker --loglevel=info -B
    environment:
      - DVALIN_CELERY_BROKER_URL=${DVALIN_CELERY_BROKER_URL}
      - DVALIN_CELERY_RESULT_BACKEND=${DVALIN_CELERY_RESULT_BACKEND}
      - DVALIN_S3_ENDPOINT=${DVALIN_S3_ENDPOINT}
      - DVALIN_S3_ACCESS_KEY=${DVALIN_S3_ACCESS_KEY}
      - DVALIN_S3_SECRET_KEY=${DVALIN_S3_SECRET_KEY}
    depends_on:
      - redis
    volumes:
      - ../data:/data
      - ./__scraper_cache__:/usr/src/__scraper_cache__

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
