version: '3.8'

services:
  event_agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-localdev
    environment:
      - DVALIN_REPO_ROOT_DIR=/usr/src/repo/dvalin-data
    volumes:
      - ..:/usr/src/repo/dvalin-data
      - ./__scraper_cache__:/usr/src/app/__scraper_cache__
